---
version: "3.8"
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    image: clitool-image
    volumes:
      - data:/app/data
volumes:
  data:
